version: "3.9"

services:
  web: # AKA client
    container_name: tcp-web
    stdin_open: true
    build: ./web
    environment:
      - PORT=${WEB_PORT:-4191}
      - ENV=${ENV:-production}
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:${API_PORT:-4190}}
      - REACT_APP_WEB_URL=${REACT_APP_WEB_URL:-http://localhost:${WEB_PORT:-4191}}
    depends_on:
      - api
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
    ports:
      - ${WEB_PORT:-4191}:${WEB_PORT:-4191}

  api:
    container_name: tcp-api
    stdin_open: true
    build: ./api
    environment:
      - PORT=${API_PORT:-4190}
      - DATABASE_URL=${DATABASE_URL:-mongodb://mongo/the-clipping-project}
      - ENV=${ENV:-production}
    depends_on:
      - mongo
    volumes:
      - ./api:/app/api
      - ./clips:/api/videos
      - /app/api/node_modules
    ports:
      - ${API_PORT:-4190}:${API_PORT:-4190}

  mongo:
    image: mongo:latest
    container_name: tcp-database
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
